import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/
`;

const prod = process.argv[2] === 'production';

const vaultIdx = process.argv.indexOf('--vault');
const vaultDir = vaultIdx > -1 ? process.argv[vaultIdx + 1] : null;

const outdir = vaultDir
	? path.join(vaultDir, '.obsidian', 'plugins', 'sobriety-tracker')
	: '.';

const outfile = path.join(outdir, 'main.js');

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile,
	minify: prod,
});

async function copyAssets() {
	if (vaultDir) {
		fs.cpSync('manifest.json', path.join(outdir, 'manifest.json'), { force: true });
		fs.cpSync('styles.css', path.join(outdir, 'styles.css'), { force: true });
		console.log(`Assets copied to ${outdir}`);
	}
}

if (prod) {
	await context.rebuild();
	process.exit(0);
}

if (vaultDir) {
	await copyAssets();
	console.log(`Watching... output to ${outdir}`);
	await context.watch();
} else {
	await context.rebuild();
	process.exit(0);
}
